# Generated by Django 4.0.7 on 2023-05-18 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=200)),
                ('product_text', models.CharField(blank=True, max_length=200)),
                ('price', models.FloatField(default=0)),
                ('product_amount', models.IntegerField(default=0)),
                ('product_numbering', models.IntegerField(default=0)),
                ('product_category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventorycontrol.category')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_price', models.FloatField(default=0)),
                ('product_amount', models.IntegerField(default=0)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorycontrol.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('total_price', models.FloatField(default=0)),
                ('order_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorycontrol.product')),
            ],
        ),
    ]
