# Generated by Django 4.0.7 on 2023-05-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voorraadbeheer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_amount',
            field=models.IntegerField(default=0),
        ),
    ]
